# Generated by Django 4.2.5 on 2023-10-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='article/', verbose_name='изображение')),
                ('quantity', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('sign', models.BooleanField(default=True, verbose_name='признак публикации')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
