# Generated by Django 4.2.5 on 2023-09-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_mailing_frequency_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.IntegerField(choices=[('1', 'создана'), ('2', 'запущена'), ('3', 'завершена')], default='создана', verbose_name='статус рассылки(завершена, создана, запущена)'),
        ),
    ]
