# Generated by Django 4.2.5 on 2023-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_client_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='service.client'),
        ),
    ]
