# Generated by Django 4.2.5 on 2023-09-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(max_length=15, verbose_name='статус попытки'),
        ),
    ]
